In [1]:
import pandas as pd
import numpy as np

In [4]:
text={"text":["People watch Aiyug","Aiyug watch Aiyug","People write comment","Aiyug write comment"],"Output":[1,1,0,0]}

In [5]:
text=pd.DataFrame(text)

In [6]:
text

text  Output
0    People watch Aiyug       1
1     Aiyug watch Aiyug       1
2  People write comment       0
3   Aiyug write comment       0

In [7]:
from sklearn.feature_extraction.text import CountVectorizer

In [8]:
cv=CountVectorizer(lowercase=True,stop_words='english',binary=True)

In [9]:
bow=cv.fit_transform(text['text'])

In [11]:
cv.vocabulary_

{'people': 2, 'watch': 3, 'aiyug': 0, 'write': 4, 'comment': 1}

In [14]:
print(bow[0].toarray())
print(bow[1].toarray())
print(bow[2].toarray())
print(bow[3].toarray())

[[1 0 1 1 0]]
[[1 0 0 1 0]]
[[0 1 1 0 1]]
[[1 1 0 0 1]]


In [15]:
cv.transform(["hello comment my name watch is saksham"]).toarray()

array([[0, 1, 0, 1, 0]])

N grams

In [16]:
from nltk import ngrams
from nltk.tokenize import word_tokenize
text = "I love natural language processing"
tokens=word_tokenize(text)
n=3
trigrams = ngrams(tokens, n)
trigrams = list(trigrams)
print(trigrams)

[('I', 'love', 'natural'), ('love', 'natural', 'language'), ('natural', 'language', 'processing')]
