In [1]:
import numpy as np

In [2]:
np.__version__

'2.3.1'

In [3]:
lst =[1,2,3,4,5,6,6]
arr=np.array(lst)

In [4]:
arr

array([1, 2, 3, 4, 5, 6, 6])

In [5]:
arr=np.array([1,2,3,4,5,6,6])

In [6]:
arr

array([1, 2, 3, 4, 5, 6, 6])

In [7]:
lst =[1,2,3,4,5,6,6]
print("type of array ",type(lst))
arr=np.array(lst)
print(arr)
print("type of array ",type(arr))

type of array  <class 'list'>
[1 2 3 4 5 6 6]
type of array  <class 'numpy.ndarray'>


In [8]:
arr=np.array(list(range(1,21)))
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [9]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [10]:
np.zeros((5,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [11]:
np.ones((5,10))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [12]:
arr=np.linspace(1,10,5)
arr

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [13]:
# 1d array convert into 2d array
arr=np.arange(0,30)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [14]:
arr.reshape(3,10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [15]:
arr=np.random.randint(1,5,9)    # 1 starting point, 5 ending point, 9 is the number of elements
arr

array([1, 3, 3, 3, 3, 2, 2, 3, 1], dtype=int32)

In [16]:
arr=np.random.randint(1,5,(3,3))    
arr

array([[3, 2, 1],
       [2, 1, 2],
       [4, 4, 3]], dtype=int32)

In [17]:
arr=np.random.random(10)   
arr

array([0.98135986, 0.65772823, 0.10560131, 0.18894798, 0.48978558,
       0.9048247 , 0.82149397, 0.24564827, 0.3614013 , 0.89503694])

In [18]:
arr=np.random.random((5,10))
arr

array([[0.9906899 , 0.20542735, 0.41570894, 0.85097378, 0.83588563,
        0.44780492, 0.51210161, 0.09999093, 0.05893647, 0.08713444],
       [0.4213561 , 0.40890927, 0.34886494, 0.31532464, 0.73845738,
        0.46001266, 0.45670535, 0.24181372, 0.18694011, 0.42549294],
       [0.50100524, 0.97727703, 0.98374895, 0.83720932, 0.7587137 ,
        0.59374669, 0.48482856, 0.76703927, 0.34669922, 0.21177957],
       [0.52827814, 0.71220862, 0.11243165, 0.6124064 , 0.6633977 ,
        0.31742365, 0.06245909, 0.69392181, 0.18736578, 0.03254807],
       [0.01807561, 0.09156915, 0.55147661, 0.76182902, 0.58456061,
        0.59083088, 0.09215896, 0.01015338, 0.05654062, 0.43404095]])

In [3]:
arr=np.arange(60).reshape(12,5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59]])

In [20]:
print(arr.shape)
print(arr.size)
print(arr.dtype)
print(arr.ndim)

(12, 5)
60
int64
2


In [ ]:
arr.flatten() # copy of the array in 1d

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

In [ ]:
arr.ravel()  # returns a view of the array in 1d, if possible

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

In [4]:
arr.shape

(12, 5)

In [24]:
arr.T

array([[ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55],
       [ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46, 51, 56],
       [ 2,  7, 12, 17, 22, 27, 32, 37, 42, 47, 52, 57],
       [ 3,  8, 13, 18, 23, 28, 33, 38, 43, 48, 53, 58],
       [ 4,  9, 14, 19, 24, 29, 34, 39, 44, 49, 54, 59]])

In [25]:
arr.T.shape

(5, 12)

In [26]:
arr=np.arange(30)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [27]:
arr[12]


np.int64(12)

In [28]:
arr[20]

np.int64(20)

In [29]:
arr[0:12]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [30]:
arr[0]=100

In [31]:
arr

array([100,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29])

In [32]:
arr=np.arange(60).reshape(12,5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59]])

In [33]:
arr[1,1]

np.int64(6)

In [34]:
arr[1,3:5]

array([8, 9])

In [35]:
arr[0:5,1]

array([ 1,  6, 11, 16, 21])

In [36]:
arr[1,1]

np.int64(6)

In [37]:
arr[1,1]=100
arr

array([[  0,   1,   2,   3,   4],
       [  5, 100,   7,   8,   9],
       [ 10,  11,  12,  13,  14],
       [ 15,  16,  17,  18,  19],
       [ 20,  21,  22,  23,  24],
       [ 25,  26,  27,  28,  29],
       [ 30,  31,  32,  33,  34],
       [ 35,  36,  37,  38,  39],
       [ 40,  41,  42,  43,  44],
       [ 45,  46,  47,  48,  49],
       [ 50,  51,  52,  53,  54],
       [ 55,  56,  57,  58,  59]])

In [38]:
arr[11,4]

np.int64(59)

In [39]:
arr[-1,-1]

np.int64(59)

In [40]:
arr[11][-1]

np.int64(59)

In [41]:
arr=np.array(np.arange(225).reshape(5,15,3))
arr

array([[[  0,   1,   2],
        [  3,   4,   5],
        [  6,   7,   8],
        [  9,  10,  11],
        [ 12,  13,  14],
        [ 15,  16,  17],
        [ 18,  19,  20],
        [ 21,  22,  23],
        [ 24,  25,  26],
        [ 27,  28,  29],
        [ 30,  31,  32],
        [ 33,  34,  35],
        [ 36,  37,  38],
        [ 39,  40,  41],
        [ 42,  43,  44]],

       [[ 45,  46,  47],
        [ 48,  49,  50],
        [ 51,  52,  53],
        [ 54,  55,  56],
        [ 57,  58,  59],
        [ 60,  61,  62],
        [ 63,  64,  65],
        [ 66,  67,  68],
        [ 69,  70,  71],
        [ 72,  73,  74],
        [ 75,  76,  77],
        [ 78,  79,  80],
        [ 81,  82,  83],
        [ 84,  85,  86],
        [ 87,  88,  89]],

       [[ 90,  91,  92],
        [ 93,  94,  95],
        [ 96,  97,  98],
        [ 99, 100, 101],
        [102, 103, 104],
        [105, 106, 107],
        [108, 109, 110],
        [111, 112, 113],
        [114, 115, 116],
        [117, 118, 11

In [42]:
arr.ndim,arr.shape,arr.size,arr.dtype

(3, (5, 15, 3), 225, dtype('int64'))

In [43]:
arr[0]

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23],
       [24, 25, 26],
       [27, 28, 29],
       [30, 31, 32],
       [33, 34, 35],
       [36, 37, 38],
       [39, 40, 41],
       [42, 43, 44]])

In [44]:
arr[2]

array([[ 90,  91,  92],
       [ 93,  94,  95],
       [ 96,  97,  98],
       [ 99, 100, 101],
       [102, 103, 104],
       [105, 106, 107],
       [108, 109, 110],
       [111, 112, 113],
       [114, 115, 116],
       [117, 118, 119],
       [120, 121, 122],
       [123, 124, 125],
       [126, 127, 128],
       [129, 130, 131],
       [132, 133, 134]])

In [45]:
arr[0,2:]

array([[ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23],
       [24, 25, 26],
       [27, 28, 29],
       [30, 31, 32],
       [33, 34, 35],
       [36, 37, 38],
       [39, 40, 41],
       [42, 43, 44]])

In [46]:
arr[0,2:,2]

array([ 8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 44])

In [47]:
arr[0,3:5]

array([[ 9, 10, 11],
       [12, 13, 14]])

In [48]:
arr[:,0,:]

array([[  0,   1,   2],
       [ 45,  46,  47],
       [ 90,  91,  92],
       [135, 136, 137],
       [180, 181, 182]])

In [49]:
arr[:,0:1,0:1]

array([[[  0]],

       [[ 45]],

       [[ 90]],

       [[135]],

       [[180]]])

In [50]:
arr[0,1,1]=1000

In [51]:
arr[0,1,1]

np.int64(1000)

In [52]:
arr=np.array([1,5,6,9,3])

In [53]:
arr.sort()

In [54]:
arr+2

array([ 3,  5,  7,  8, 11])

In [55]:
arr-2

array([-1,  1,  3,  4,  7])

In [56]:
arr*2

array([ 2,  6, 10, 12, 18])

In [57]:
arr/2

array([0.5, 1.5, 2.5, 3. , 4.5])

In [58]:
arr1=np.array([1,2,3,5])
arr2=np.array([1,6,3,5])

In [59]:
arr1+arr2

array([ 2,  8,  6, 10])

In [60]:
arr1-arr2

array([ 0, -4,  0,  0])

In [61]:
arr1*arr2

array([ 1, 12,  9, 25])